// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.ai.personalizer.implementation;

import com.azure.ai.personalizer.implementation.models.ErrorResponseException;
import com.azure.ai.personalizer.implementation.models.RewardRequest;
import com.azure.core.annotation.BodyParam;
import com.azure.core.annotation.ExpectedResponses;
import com.azure.core.annotation.HeaderParam;
import com.azure.core.annotation.Host;
import com.azure.core.annotation.HostParam;
import com.azure.core.annotation.PathParam;
import com.azure.core.annotation.Post;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceInterface;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.annotation.UnexpectedResponseExceptionType;
import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.RestProxy;
import com.azure.core.util.Context;
import reactor.core.publisher.Mono;

/** An instance of this class provides access to all the operations defined in Events. */
public final class EventsImpl {
    /** The proxy service used to perform REST calls. */
    private final EventsService service;

    /** The service client containing this operation class. */
    private final PersonalizerClientV1Preview3Impl client;

    /**
     * Initializes an instance of EventsImpl.
     *
     * @param client the instance of the service client containing this operation class.
     */
    EventsImpl(PersonalizerClientV1Preview3Impl client) {
        this.service = RestProxy.create(EventsService.class, client.getHttpPipeline(), client.getSerializerAdapter());
        this.client = client;
    }

    /**
     * The interface defining all the services for PersonalizerClientV1Preview3Events to be used by the proxy service to
     * perform REST calls.
     */
    @Host("{Endpoint}/personalizer/v1.1-preview.3")
    @ServiceInterface(name = "PersonalizerClientV1")
    private interface EventsService {
        @Post("/events/{eventId}/reward")
        @ExpectedResponses({204})
        @UnexpectedResponseExceptionType(ErrorResponseException.class)
        Mono<Response<Void>> reward(
                @HostParam("Endpoint") String endpoint,
                @PathParam("eventId") String eventId,
                @BodyParam("application/json") RewardRequest reward,
                @HeaderParam("Accept") String accept,
                Context context);

        @Post("/events/{eventId}/activate")
        @ExpectedResponses({204})
        @UnexpectedResponseExceptionType(ErrorResponseException.class)
        Mono<Response<Void>> activate(
                @HostParam("Endpoint") String endpoint,
                @PathParam("eventId") String eventId,
                @HeaderParam("Accept") String accept,
                Context context);
    }

    /**
     * Report reward between 0 and 1 that resulted from using the action specified in rewardActionId, for the specified
     * event.
     *
     * @param eventId The event id this reward applies to.
     * @param reward The reward should be a floating point number, typically between 0 and 1.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the completion.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> rewardWithResponseAsync(String eventId, RewardRequest reward, Context context) {
        final String accept = "application/json";
        return service.reward(this.client.getEndpoint(), eventId, reward, accept, context);
    }

    /**
     * Report that the specified event was actually used (e.g. by being displayed to the user) and a reward should be
     * expected for it.
     *
     * @param eventId The event ID to be activated.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ErrorResponseException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the completion.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<Void>> activateWithResponseAsync(String eventId, Context context) {
        final String accept = "application/json";
        return service.activate(this.client.getEndpoint(), eventId, accept, context);
    }
}
